### ISSUE TITLE
Sync error in 4.0.1

### ISSUE THREAD

**Issue by Dekadinious** [clerkio/clerk-woocommerce#54]
As I understand it the 4.0.1 version fixed some issues with facets breaking the search result page. But after updating we get a sync error when syncing to Clerk. The positive thing is that the search page works now:

![image](https://user-images.githubusercontent.com/37292177/204722456-df0d3171-f988-4ae7-b8a1-4b91a9c76dfc.png)

Tagging you @FoulBachelor in the hope of a quick fix since we are stuck without options to sync products to Clerk right now :) We can't roll back because the previous working version of the plugin synced 0 as the price in 50 % of the syncs.

**Comment by FoulBachelor** [comment]
Hi Dekadinious,
The only change to the sync is the orderby argument for pagination, perhaps your problem could come from there.

https://github.com/clerkio/clerk-woocommerce/commit/96103f6510abd596d5dcaadeda878ad5232d1125

If you could include some details as to what fails in your sync, in terms of your current issue, I can be more helpful. But currently I have very little information on your situation.

Here is a sync from the latest version of WP + WooComm from a test site which completes on 4.0.1 from my own tests.
![screencapture-my-clerk-io-2022-11-30-08_03_22](https://user-images.githubusercontent.com/89036433/204729853-5c55b50e-d9b2-4424-ace3-c0f15a01a798.png)

If you can clarify whether the orderby argument addresses the issue, it would be appreaciated. 

Otherwise I would very much like some more details regarding the page of failure. I would also like some info on your price info, and whether or not the 0 prices would always be fixed by a full sync vs realtime update, and which methods you use to access prices in the admin. This is due to the hooks for the realtime updates being a bit different depending on way an item is changed.

 @Dekadinious

**Comment by Dekadinious** [comment]
Yes, changing back to "product_id" fixes the issue. Which is quite weird as wc_get_products doesn't accept that as an argument? It should accept "name" or "ID" but not "product_id", and the latter is all that works?

As for the price problem it only appeared after rolling back to an old version because of a problem with the search page (before fixing facet quote escaping). It would appear randomly and a full sync would fix it. We'll keep an eye on it and submit a new issue if it persists.

But for this issue, I don't know why "name" is not working. I'll try to log it and come back here.

**Comment by Dekadinious** [comment]
Ok, can't actually repeat the problem now. Might be an issue at Clerk at the time of testing earlier :) Name works fine! @FoulBachelor

**Comment by FoulBachelor** [comment]
Hi Dekadinious, 

Thanks for the quick reply, and taking time to confirm your findings.

I am happy to hear that it is working now, this is what we want! 

Also many thanks for the other improvements you have submitted, it is very appreciated. <3

**Comment by Dekadinious** [comment]
More will come as problems appear in our logs ;) :)

**Comment by FoulBachelor** [comment]
All good things come in batches ;)
